# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
 
Vagrant.configure("2") do |config|
 
  # nodes
  $node_count = 2
  (1..$node_count).each do |id|
     config.vm.define "node#{id}" do |nodes|
         nodes.vm.box = "centos/7"
         nodes.vm.hostname = "node#{id}"
         nodes.vm.network :private_network, :ip => "192.168.77.#{20+id}"
 
         nodes.vm.provider :libvirt do |setting|
              setting.memory = 512
              setting.cpus = 1
         end
    end
 end

  # Puppet Enterprise 2018 and Puppet Tasks
  config.vm.define "master" do |master|
      master.vm.box = "centos/7"
      master.vm.hostname = "master"
      master.vm.network :private_network, :ip => "192.168.77.100"

      master.vm.provider :libvirt do |setting|
           setting.memory = 2048
           setting.cpus = 2
      end
   end
 
  # Tools of DevOps: jenkins and Vault 
  config.vm.define "devops" do |devops|
      devops.vm.box = "centos/7"
      devops.vm.hostname = "devops"
      devops.vm.network :private_network, :ip => "192.168.77.200"

      devops.vm.provider :libvirt do |setting|
           setting.memory = 2048
           setting.cpus = 2
      end
   end


end
